version: '3.8'

services:
  web:
    build: .
    container_name: api_php
    restart: unless-stopped
    ports:
      - "8080:80"            # Cliente → Apache
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_NAME: cannabis_db
      DB_USER: appsociacion
      DB_PASS: admin
      JWT_SECRET: l4t4r4r4ll3v41v3st12ll3n0d3c4sc4b3l3s
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:     ${MYSQL_DATABASE}
      MYSQL_USER:         ${MYSQL_USER}
      MYSQL_PASSWORD:     ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"    # Aquí el puerto para acceder a phpMyAdmin
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
