services:
  - type: web
    runtime: docker
    name: api-php
    repo: https://github.com/HLY-SHT/api-rest-appsociacion.git
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_NAME
        value: cannabis_db
      - key: DB_USER
        value: appsociacion
      - key: DB_PASS
        value: admin
      - key: JWT_SECRET
        sync: false
    plan: free

  - type: pserv
    runtime: docker
    name: db
    dockerImage: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: cannabis_db
      - key: MYSQL_USER
        value: appsociacion
      - key: MYSQL_PASSWORD
        sync: false
    plan: starter

  - type: web
    runtime: docker
    name: phpmyadmin
    dockerImage: phpmyadmin/phpmyadmin
    envVars:
      - key: PMA_HOST
        value: db
      - key: PMA_USER
        value: appsociacion
      - key: PMA_PASSWORD
        sync: false
    plan: free
