services:
  # API PHP + Apache (construido desde Dockerfile)
  - type: web
    runtime: docker
    name: api-php
    repo: https://github.com/HLY-SHT/api-rest-appsociacion.git
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://cannabisdb_user:hg183syyEfPij9Dj1QsA1XZUmBjo4kI9@dpg-d18qvuh5pdvs73cs1eq0-a/cannabisdb
      - key: JWT_SECRET
        sync: false
    plan: free

  # Gestor de base de datos PostgreSQL: Adminer
  - type: web
    runtime: docker
    name: adminer
    image:
      url: adminer:latest
    ports:
      - 8081:8080
    plan: free
