services:
  # 1) API PHP + Apache
  - type: web           # web service
    runtime: docker     # construye desde Dockerfile
    name: api-php
    repo: https://github.com/HLY-SHT/api-rest-appsociacion.git
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_NAME
        value: cannabis_db
      - key: DB_USER
        value: appsociacion
      - key: DB_PASS
        value: admin
      - key: JWT_SECRET
        sync: false     # valor secreto que Render te pedirá
    plan: free

  # 2) MySQL como servicio privado
  - type: pserv         # private service
    runtime: docker     # usa una imagen Docker
    name: db
    dockerImage: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        sync: false     # Render te preguntará este secreto
      - key: MYSQL_DATABASE
        value: cannabis_db
      - key: MYSQL_USER
        value: appsociacion
      - key: MYSQL_PASSWORD
        sync: false     # Render te preguntará este secreto
    plan: starter       # los private services no pueden ser free

  # 3) phpMyAdmin (web público)
  - type: web
    runtime: docker
    name: phpmyadmin
    dockerImage: phpmyadmin/phpmyadmin
    envVars:
      - key: PMA_HOST
        value: db
      - key: PMA_USER
        value: appsociacion
      - key: PMA_PASSWORD
        sync: false     # mismo secreto que MYSQL_PASSWORD
    plan: free
